DROP USER IF EXISTS 'ADMIN_UNIVERSITY_GUI';

CREATE USER 'ADMIN_UNIVERSITY_GUI'@'%' IDENTIFIED BY '1234';

GRANT SELECT,INSERT,UPDATE,DELETE
	ON `university2`.* 
    TO 'ADMIN_UNIVERSITY_GUI'@'%';
    